version: '3.8'

services:
  expo:
    build:
      context: .
    container_name: expo-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 19000:19000   # Metro bundler (para móviles)
      - 19001:19001   # Conexión con dispositivos
      - 19002:19002   # Expo DevTools
      - 8081:8081     # Web version
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
