version: '3.8'

services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: node-express-prisma-backend
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env
    restart: unless-stopped
    depends_on:
      - database

  expo:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: expo-dev-frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - 19000:19000   # Metro bundler (para móviles)
      - 19001:19001   # Conexión con dispositivos
      - 19002:19002   # Expo DevTools
      - 8081:8081     # Web version
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - app

  database:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
