version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-express-prisma
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

