version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-express-prisma
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped

